[package]
name = "minedmap"
version = "0.1.0"
edition = "2021"
license = "MIT"
default-run = "minedmap"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
bincode = "1.3.3"
bytemuck = "1.13.0"
clap = { version = "4.1.4", features = ["derive"] }
enumflags2 = "0.7.5"
fastnbt = "2.3.2"
flate2 = "1.0.25"
futures-util = "0.3.28"
glam = "0.24.0"
image = { version = "0.24.5", default-features = false, features = ["png"] }
indexmap = { version = "2.0.0", features = ["serde"] }
itertools = "0.11.0"
lru = "0.11.0"
num-integer = "0.1.45"
num_cpus = "1.16.0"
rayon = "1.7.0"
rustc-hash = "1.1.0"
serde = { version = "1.0.152", features = ["rc"] }
serde_json = "1.0.99"
tokio = { version = "1.31.0", features = ["rt", "parking_lot", "sync"] }
zstd = "0.12.3"

[features]
default = ["zlib-ng"]
zlib-ng = ["flate2/zlib-ng"]
