[package]
name = "minedmap"
version = "0.1.0"
edition = "2021"
license = "BSD-2-Clause"
default-run = "minedmap"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.4", features = ["derive"] }
fastnbt = "2.3.2"
flate2 = "1.0.25"
itertools = "0.10.5"
serde = "1.0.152"
